// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package documents

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func DocumentPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"parent-div\"><p class=\"pr-4 pb-4 text-xl font-bold\">Documents</p><form id=\"form\" hx-swap=\"outerHTML\" hx-target=\"#parent-div\" hx-encoding=\"multipart/form-data\" hx-post=\"/documents\"><div class=\"rounded-md border border-dashed border-black bg-gray-50 p-4 shadow-md w-36\"><label for=\"file\" class=\"flex flex-col items-center gap-2 cursor-pointer\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-10 w-10 fill-white stroke-black\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z\"></path></svg> <span class=\"text-gray-600 font-medium\">Upload file</span></label> <input id=\"file\" name=\"file\" type=\"file\" class=\"hidden\"></div><div><span id=\"file-name\" class=\"text-lg\"></span></div><button class=\"mt-2 rounded-lg border border-black bg-black px-12 py-3 text-sm font-medium text-white\">Upload</button></form></div><script>\r\n\t\tconst fileInput = document.getElementById('file');\r\n\t\tconst fileNameSpan = document.getElementById('file-name');\r\n\r\n\t\tfileInput.addEventListener('change', function() {\r\n\t\t\tif (fileInput.files.length > 0) {\r\n\t\t\t\tfileNameSpan.textContent = fileInput.files[0].name;\r\n\t\t\t} \r\n\t\t});\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
